import 'nz_trip_models.dart';

/// Seed data for NZ trip (2 people / 14 days).
/// Pink-source items → Cat; yellow-highlighted → priority.
abstract final class NzTripSeed {
  static const tripId = 'shared';

  static const meColor = 0xFF1B7A6E; // forest teal
  static const catColor = 0xFFE07A5F; // warm coral

  static TripMeta meta() => TripMeta(
        title: 'NZ Trip · 14 days',
        seeded: true,
        departureDate: '2026-08-29',
        owners: const [
          TripOwner(id: 'me', label: 'Me', colorArgb: meColor),
          TripOwner(id: 'cat', label: 'Cat', colorArgb: catColor),
        ],
        bags: const [
          TripBag(id: 'carry_on', name: 'Carry-on', order: 0, note: ''),
          TripBag(id: 'checked', name: 'Checked', order: 1, note: ''),
          TripBag(
            id: 'personal',
            name: 'Personal item',
            order: 2,
            note: '',
          ),
        ],
        weatherLegs: const [
          // Arrival (North Island)
          WeatherLeg(
            id: 'leg_akl',
            name: 'Auckland',
            lat: -36.8485,
            lon: 174.7633,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          // South Island — major towns & stops (trip window)
          WeatherLeg(
            id: 'leg_nsn',
            name: 'Nelson',
            lat: -41.2706,
            lon: 173.2840,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_pcn',
            name: 'Picton',
            lat: -41.2907,
            lon: 174.0010,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_bhe',
            name: 'Blenheim',
            lat: -41.5134,
            lon: 173.9612,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_kbz',
            name: 'Kaikōura',
            lat: -42.4008,
            lon: 173.6814,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_han',
            name: 'Hanmer Springs',
            lat: -42.5227,
            lon: 172.8286,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_chc',
            name: 'Christchurch',
            lat: -43.5321,
            lon: 172.6362,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_aka',
            name: 'Akaroa',
            lat: -43.8038,
            lon: 172.9683,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_gm',
            name: 'Greymouth',
            lat: -42.4504,
            lon: 171.2108,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_hkk',
            name: 'Hokitika',
            lat: -42.7167,
            lon: 170.9667,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_pun',
            name: 'Punakaiki',
            lat: -42.1090,
            lon: 171.3320,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_fzj',
            name: 'Franz Josef',
            lat: -43.3881,
            lon: 170.1825,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_fox',
            name: 'Fox Glacier',
            lat: -43.4650,
            lon: 170.0178,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_arp',
            name: "Arthur's Pass",
            lat: -42.9417,
            lon: 171.5667,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_tek',
            name: 'Lake Tekapo',
            lat: -44.0047,
            lon: 170.4761,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_mtc',
            name: 'Aoraki / Mt Cook',
            lat: -43.7340,
            lon: 170.0966,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_twz',
            name: 'Twizel',
            lat: -44.2585,
            lon: 170.1009,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_wan',
            name: 'Wānaka',
            lat: -44.7000,
            lon: 169.1500,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_zqn',
            name: 'Queenstown',
            lat: -45.0312,
            lon: 168.6626,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_crom',
            name: 'Cromwell',
            lat: -45.0380,
            lon: 169.1950,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_teu',
            name: 'Te Anau',
            lat: -45.4145,
            lon: 167.7180,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_mfn',
            name: 'Milford Sound',
            lat: -44.6717,
            lon: 167.9256,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_oam',
            name: 'Oamaru',
            lat: -45.0975,
            lon: 170.9704,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_dud',
            name: 'Dunedin',
            lat: -45.8788,
            lon: 170.5028,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_ivc',
            name: 'Invercargill',
            lat: -46.4132,
            lon: 168.3538,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
          WeatherLeg(
            id: 'leg_sti',
            name: 'Stewart Island',
            lat: -46.8980,
            lon: 168.1270,
            startDate: '2026-08-29',
            endDate: '2026-09-15',
          ),
        ],
        categories: const [
          TripCategory(
            id: 'essentials',
            name: 'Essentials & Documents',
            order: -1,
            isEssential: true,
          ),
          TripCategory(id: 'medicine', name: 'Medicine', order: 0),
          TripCategory(id: 'gear', name: 'Gear & Misc', order: 1),
          TripCategory(id: 'food', name: 'Food', order: 2),
          TripCategory(
            id: 'local',
            name: 'Local (buy in NZ)',
            order: 3,
            isLocal: true,
          ),
        ],
      );

  static List<TripItem> items() {
    TripItem i(
      String id,
      String name,
      String cat,
      String owner,
      String qty, {
      bool priority = false,
      bool local = false,
      ItemKind kind = ItemKind.goods,
      String bagId = '',
      bool liquid = false,
      bool med = false,
      bool biosecurity = false,
    }) =>
        TripItem(
          id: id,
          name: name,
          categoryId: cat,
          ownerId: owner,
          recommendedQty: qty,
          quantity: qty,
          priority: priority,
          buyLocation:
              local ? BuyLocation.inNz : BuyLocation.beforeDeparture,
          kind: kind,
          bagId: bagId,
          isLiquidOver100ml: liquid,
          isMedication: med,
          isBiosecurity: biosecurity,
        );

    return [
      // —— Essentials & Documents ——
      i('e01', 'Passport', 'essentials', 'me', '1 each',
          kind: ItemKind.essential, priority: true, bagId: 'personal'),
      i('e02', 'Visa / NZ eTA + IVL', 'essentials', 'me', '1 each',
          kind: ItemKind.essential, priority: true, bagId: 'personal'),
      i('e03', 'Flight tickets / boarding passes', 'essentials', 'me', '1 set',
          kind: ItemKind.essential, priority: true, bagId: 'personal'),
      i('e04', 'Travel insurance', 'essentials', 'me', '1 policy (shared)',
          kind: ItemKind.essential, priority: true, bagId: 'personal'),
      i('e05', "Driver's license + International Driving Permit", 'essentials',
          'me', '1 set',
          kind: ItemKind.essential, priority: true, bagId: 'personal'),
      i('e06', 'Accommodation bookings / confirmations', 'essentials', 'me',
          '1 set',
          kind: ItemKind.essential, bagId: 'personal'),
      i('e07', 'Cash + cards (notify bank of travel)', 'essentials', 'me',
          'both wallets',
          kind: ItemKind.essential, priority: true, bagId: 'personal'),
      i('e08', 'Phone chargers', 'essentials', 'me', '2 (1 each)',
          kind: ItemKind.essential, bagId: 'carry_on'),
      i('e09', 'NZ power adapter (Type I plug)', 'essentials', 'me', '1–2',
          kind: ItemKind.essential, bagId: 'carry_on'),
      i('e10', 'SIM / eSIM', 'essentials', 'me', '1–2',
          kind: ItemKind.essential, bagId: 'personal'),
      i('e11', 'Emergency contacts / embassy info', 'essentials', 'me',
          'saved offline + paper',
          kind: ItemKind.essential, bagId: 'personal'),

      // —— Medicine ——
      i('m01', '止泻药 (anti-diarrheal)', 'medicine', 'me', '1 strip (6–10 tabs)',
          med: true, bagId: 'carry_on'),
      i('m02', 'Gastric (antacid)', 'medicine', 'me', '1 strip (~10)',
          med: true, bagId: 'carry_on'),
      i('m03', 'Panadol', 'medicine', 'me', '1 box (10–20)',
          med: true, bagId: 'carry_on'),
      i('m04', 'Flu (Morning)', 'medicine', 'cat', '1 strip (6–10)',
          med: true, bagId: 'carry_on'),
      i('m05', 'Flu (Night)', 'medicine', 'cat', '1 strip (6–10)',
          med: true, bagId: 'carry_on'),
      i('m06', 'Zytec (antihistamine)', 'medicine', 'me', '1 strip (~10)',
          med: true, bagId: 'carry_on'),
      i('m07', '缓解疲劳 (fatigue relief)', 'medicine', 'me', '1 small pack',
          med: true, bagId: 'carry_on'),
      i('m08', 'Dr Yen (Request Letter)', 'medicine', 'cat', '1 (document)',
          med: true, bagId: 'personal'),
      i('m09', '风油 (medicated oil)', 'medicine', 'cat', '1 bottle',
          med: true, liquid: true, bagId: 'checked'),
      i('m10', 'Sore throat', 'medicine', 'me', '1 pack',
          med: true, bagId: 'carry_on'),
      i('m11', '金嗓子 (throat lozenge)', 'medicine', 'me', '1 pack',
          med: true, bagId: 'carry_on'),
      i('m12', 'Vitamin C', 'medicine', 'me', '1 tube/bottle (~14–20)',
          med: true, bagId: 'carry_on'),
      i('m13', 'Probiotic', 'medicine', 'me', '1 box (~14 sachets)',
          med: true, bagId: 'carry_on'),
      i('m14', 'Flu GO', 'medicine', 'me', '1 box',
          med: true, bagId: 'carry_on'),

      // —— Gear & Misc ——
      i('g01', '露营毯子/垫 (camping blanket/mat)', 'gear', 'me', '1–2',
          bagId: 'checked'),
      i('g02', '电煲 (electric cooker)', 'gear', 'me', '1 (shared)',
          priority: true, bagId: 'checked'),
      i('g03', 'Tripod', 'gear', 'cat', '1', bagId: 'checked'),
      i('g04', 'Car Phone Holder', 'gear', 'me', '1', bagId: 'checked'),
      i('g05', '一次性床单 (disposable bed sheet)', 'gear', 'cat', '2–3',
          bagId: 'checked'),
      i('g06', '一次性毛巾 (disposable towels)', 'gear', 'cat',
          '8–10 (≈1 / 3 days each)', bagId: 'checked'),
      i('g07', '一次性餐具 (spoon/fork/bowl)', 'gear', 'cat', '1 pack (~20 sets)',
          bagId: 'checked'),
      i('g08', '垃圾袋 (garbage bags)', 'gear', 'me', '1 roll (~15–20)',
          bagId: 'checked'),
      i('g09', '抹脚布 (foot cloths)', 'gear', 'cat', '2', bagId: 'checked'),
      i('g10', '洗碗 铁丝球 (steel wool)', 'gear', 'me', '1–2', bagId: 'checked'),
      i('g11', '厨房铲 (spatula)', 'gear', 'me', '1', bagId: 'checked'),
      i('g12', '洗碗精 固态 (solid dish soap)', 'gear', 'me', '1', bagId: 'checked'),
      i('g13', 'Tissue (soft packs)', 'gear', 'cat',
          '4–6 total (with "Tissue x3")', bagId: 'checked'),
      i('g14', '手机架 (phone stand)', 'gear', 'me', '1', bagId: 'carry_on'),
      i('g15', '雨衣 (raincoats)', 'gear', 'cat', '2 (1 each)', bagId: 'carry_on'),
      i('g16', '雨伞 (umbrella)', 'gear', 'me', '1–2', bagId: 'checked'),
      i('g17', '口罩 (masks)', 'gear', 'cat', '1 box (10–20)', bagId: 'carry_on'),
      i('g18', 'Sanitizer', 'gear', 'me', '1–2 (60–100ml)',
          liquid: true, bagId: 'carry_on'),
      i('g19', 'Sanitizer Tissue (wet wipes)', 'gear', 'me', '1–2 packs',
          bagId: 'carry_on'),
      i('g20', 'Lotion', 'gear', 'me', '1', liquid: true, bagId: 'checked'),
      i('g21', '指甲剪 (nail clippers)', 'gear', 'me', '1', bagId: 'checked'),
      i('g22', 'Shampoo', 'gear', 'me', '1 travel (100–200ml) or buy there',
          priority: true, liquid: true, bagId: 'checked'),
      i('g23', 'Cleanser', 'gear', 'me', '1 travel size',
          priority: true, liquid: true, bagId: 'checked'),
      i('g24', '眼药水 (eye drops)', 'gear', 'me', '1–2 bottles',
          priority: true, liquid: true, med: true, bagId: 'carry_on'),
      i('g25', '暖宫 (warming patches)', 'gear', 'cat', '1 pack (~5–10)',
          bagId: 'carry_on'),
      i('g26', 'Sunscreen', 'gear', 'me', '1 (SPF50)',
          liquid: true, bagId: 'carry_on'),
      i('g27', 'Sun hat', 'gear', 'cat', '1–2', bagId: 'carry_on'),
      i('g28', 'Warm layers / thermals', 'gear', 'me', '1 set each',
          bagId: 'checked'),

      // —— Food ——
      i('f01', 'Porridge (Sachet)', 'food', 'me', '7–10 sachets',
          bagId: 'checked', biosecurity: true),
      i('f02', 'Pedas Gila', 'food', 'me', '2–3',
          bagId: 'checked', biosecurity: true),
      i('f03', 'Shin Ramen', 'food', 'me', '4–6 packs',
          bagId: 'checked', biosecurity: true),
      i('f04', '酸辣粉 (hot & sour noodles)', 'food', 'me', '2–4',
          bagId: 'checked', biosecurity: true),
      i('f05', 'Candy (HIMALA)', 'food', 'me', '3', bagId: 'carry_on'),
      i('f06', 'Paste (soup, seasoning)', 'food', 'me', '5–7 sachets',
          bagId: 'checked', biosecurity: true),
      i('f07', 'Black pepper', 'food', 'cat', '1 small bottle',
          bagId: 'checked', biosecurity: true),
      i('f08', '面条 / 米粉 (noodles / vermicelli)', 'food', 'cat', '4–6 servings',
          bagId: 'checked', biosecurity: true),

      // —— Local (buy in NZ) ——
      i('l01', '食油 (cooking oil)', 'local', 'me', '1 small bottle', local: true),
      i('l02', '面包 (bread)', 'local', 'me', '1 loaf at a time (perishable)',
          local: true),
      i('l03', 'Butter / Jam / Honey', 'local', 'me', '1 each (small)',
          local: true),
      i('l04', '老干妈 (chili crisp)', 'local', 'me', '1 jar', local: true),
      i('l05', '水 (water)', 'local', 'me',
          'as needed (NZ tap water is drinkable)',
          local: true),
    ];
  }
}
